### ISSUE TITLE
Italic naming failed

### ISSUE THREAD

**Issue by NightFurySL2001** [Omnibus-Type/Saira#15]
When checking the .otf files and using in Microsoft Office, it appeared that the italic names are wrong. In Windows Font View, instead of `Saira Condensed ExtraBold` for `SairaCondensed-ExtraBoldItalic.otf`, it show up as `Saira Condensed Condensed ExtraBold`; `SairaSemiExpanded-BlackItalic.otf` turned to `Saira SemiExpanded Semi Expanded Black` instead of `Saira SemiExpanded Black` in `SairaSemiExpanded-Black.otf`. This caused the italic font link in Office to be broken as the font names are different.

Roman:
![image](https://user-images.githubusercontent.com/33471049/104338200-366fff00-5531-11eb-99b4-22c44e51e1e9.png)

Italic:
![image](https://user-images.githubusercontent.com/33471049/104338098-1e987b00-5531-11eb-9e2f-5e78961573d6.png)

Edit: As @kenmcd mentioned, all widths except the normal have the italic style broken.

**Comment by kenmcd** [comment]
This is because the style groups are broken in all widths except the normal.
The versions available from Google Fonts have been fixed.
Those static fonts will work properly in Microsoft Office and LibreOffice.
Download here: https://fonts.google.com/download?family=Saira
That link will get the full family - static fonts in all the widths, and the two variable fonts.

**Comment by Omnibus-Type** [comment]
This is caused by a problem in the data, collected from the Glyphs source for the NAME table, specifically for the Microsoft Font Family Name. I am correcting it to upload new otf, ttf and woff2 files. Thanks for notifying us.

**Comment by NightFurySL2001** [comment]
Issue fixed. Thank you @Omnibus-Type .
